"""
Django settings for hazelsdessertshoppe project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/

For Admin:
    manage.py createsuperuser

"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

IN_PRODUCTION = True
# print('sys.argv = {}'.format(sys.argv))
if 'manage.py' in sys.argv[0]:
    IN_PRODUCTION = False
print('IN_PRODUCTION = {}'.format(IN_PRODUCTION))

if IN_PRODUCTION:
    DEBUG = True
    from hazelsdessertshoppe.secrets_prod import Secrets
else:
    from hazelsdessertshoppe.secrets_dev import Secrets
print('DEBUG = {}'.format(DEBUG))

# Use this for migrating to production!!!
from hazelsdessertshoppe.secrets_prod import Secrets


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Secrets.SECRET_KEY

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'hazelsdessertshoppe.us-west-2.elasticbeanstalk.com'
]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'copyright',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'hazelsdessertshoppe.middleware.MySessionProcessingMiddleware',
)

ROOT_URLCONF = 'hazelsdessertshoppe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'hazelsdessertshoppe/templates'),
#             os.path.join(BASE_DIR,'computers/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hazelsdessertshoppe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': Secrets.DATABASE_NAME,
        'USER': Secrets.DATABASE_USER,
        'PASSWORD': Secrets.DATABASE_PASSWORD,
        'HOST': Secrets.DATABASE_HOST,   # Or an IP Address that your DB is hosted on
        'PORT': Secrets.DATABASE_PORT,
    }
}
print(DATABASES)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_MAIN_APP = os.path.join(BASE_DIR,'hazelsdessertshoppe', 'static')
# STATIC_COMPUTERS_APP = os.path.join(BASE_DIR,'computers', 'static')
STATICFILES_DIRS = (
    STATIC_MAIN_APP,
#     STATIC_COMPUTERS_APP 
)

EMAIL_USE_TLS       = True
EMAIL_HOST          = Secrets.EMAIL_HOST
EMAIL_HOST_USER     = Secrets.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = Secrets.EMAIL_HOST_PASSWORD
EMAIL_PORT          = Secrets.EMAIL_PORT

COPY_START_YEAR = 2015
